server:
  port: 80

spring:
  application:
    name: consumer-service
# consul相关配置
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
