server:
  port: 80

spring:
  application:
    name: Feign-service

eureka:
  instance:
    instance-id: consumer80
    prefer-ip-address: true
  client:
    # 是否注册进 Eureka
    register-with-eureka: true
    # 是否从 Eureka中 获取服务信息
    fetch-registry: true
    service-url:
      defaultZone: http://www.eureka7001.com:7001/eureka/,http://www.eureka7002.com:7002/eureka/

ribbon:
  # 建立连接超时时间
  ConnectTimeout: 5000
  # 建立连接后等待服务响应时间
  ReadTimeout: 5000

logging:
  level:
    #feign日志以什么级别监控哪个接口
    com.example.feign80.service.PaymentFeignService: debug