server:
  port: 8001

# 注册进Eureka的服务名称  自定义名称
spring:
  application:
    name: cloud-payment-service
  zipkin:
    # zipkin 监控的地址
     base-url: http://localhost:9411
  sleuth:
    sampler:
      # 采样率 0-1之间  0.5表示一半采样
      probability: 1
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
  #  type: com.alibaba.druid.pool.DruidDataSource   # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver      # mysql驱动包
    url: jdbc:mysql://localhost:3306/shangguigu?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
eureka:
  # 修改主机名
  instance:
    instance-id: payment8001
      # 展示本机ip
    prefer-ip-address: true
    #eureka向客户端发起心跳的时间间隔    单位秒
    lease-renewal-interval-in-seconds: 1
    #Eureka收到最后一次心跳后等待的时间上限  单位秒  超时剔除服务
    lease-expiration-duration-in-seconds: 2
  client:
    # 自己是否注册进Eureka
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息 默认为true 单节点无所谓 集群必须为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:7001/eureka 单机
      defaultZone: http://eureka7001.com:7001/eureka/


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.i2f.springcloud.payment.dao