server:
  port: 9527

# 注册进Eureka的服务名称  自定义名称
spring:
  application:
    name: cloud-zuul-gateway

eureka:
  # 修改主机名
  instance:
    instance-id: gateway-9527.com
      # 展示本机ip
    prefer-ip-address: true

  client:
    # 自己是否注册进Eureka
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息 默认为true 单节点无所谓 集群必须为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:7001/eureka 单机
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/


zuul:
  routes:
    #    真实服务名称映射成mydept
    mydept.serviceId: cloud-payment-service
    mydept.path: /mydept/**
#    原真实服务名忽略访问   禁单个
  ignored-services: cloud-payment-service
  #  禁全部
  #  ignored-services: "*"
#  统一前缀
  prefix: /shangguigu
