server:
  port: 9527

# 注册进Eureka的服务名称  自定义名称
spring:
  application:
    name: cloud-gateway-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能 利用微服务名路由
      routes:
        - id: payment_routh   #payment_route 路由的ID，没有固定规则但是要求唯一，建议配合服务名
          #uri: http://localhost:8001           #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/get/**            #断言，路径相匹配的路由
            - After=2021-01-26T16:20:31.474+08:00[Asia/Shanghai] #这个时间之后才生效   Before之前   Between之内
            - Cookie=username,whj #用户名  key  value
            - Header=X-Request-Id,\d+  #Header请求中必须含有X-Request-Id属性  并且符合正整数的正则表达式\d+
            - Method=GET
            - Query=username,\d+  #参数必须含有username  正则表达式规则

        - id: payment_routh2   #payment_route 路由的ID，没有固定规则但是要求唯一，建议配合服务名
         # uri: http://localhost:8001           #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/payment/lb/**            #断言，路径相匹配的路由
eureka:
  # 修改主机名
  instance:
    hostname: cloud-gateway-service
  client:
    # 自己是否注册进Eureka
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息 默认为true 单节点无所谓 集群必须为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:7001/eureka 单机
      defaultZone: http://eureka7001.com:7001/eureka/


zuul:
  routes:
    #    真实服务名称映射成mydept
    mydept.serviceId: cloud-payment-service
    mydept.path: /mydept/**
#    原真实服务名忽略访问   禁单个
  ignored-services: cloud-payment-service
  #  禁全部
  #  ignored-services: "*"
#  统一前缀
  prefix: /shangguigu
