server:
  port: 7001

eureka:
  instance:
#    hostname: localhost #eureka服务器端的实例名称   单机
    hostname: eureka7001.com #eureka服务器端的实例名称  多机改名方便区分 需要修改C:\Windows\System32\drivers\etc中的host文件  增加127.0.0.1 eureka7001.com

  client:
    # false 表示不向注册中心注册自己
    register-with-eureka: false
    # false表示自己端就是注册中心 我的职责就是维护服务实例 并不需要去检索服务  开启只是方便去查询Eureka中注册的所有服务信息
    fetch-registry: false
    service-url:
      # 设置Eureka和server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka/
  server:
    # 默认保护机制 默认开启  false 关闭
    enable-self-preservation: true
    #清理无效节点的时间间隔   如果上面开启了 自我保护机制每60秒会清理一次保留的不能使用节点
    eviction-interval-timer-in-ms: 60000
