server:
  port: 83

eureka:
  client:
    # 自己是否注册进Eureka
    register-with-eureka: false
    service-url:
      #      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

#设置Feign默认等待时间  openfeign默认支持ribbon
ribbon:
  #指的是默认连接所用时间，适用于网络状态正常情况下，两端连接所用时间
  ConnectTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ReadTimeout: 5000

logging:
  level:
    #feign日志以什么级别监控哪个接口
    com.i2f.springcloud.payment.service.PaymentFeignService: debug


  #      server:
        #  port: 83
        #
        #spring:
        #  cloud:
        #    consul:
        #      host: localhost
        #      port: 8500
        #      discovery:
        #        service-name: ${spring.application.name}
        #      # hostName : 127.0.0.1
        #
      #  application:
      #    name: consul-consumer-feign-order


